# Disable the blank line at the start of the prompt
# add_newline = false

[line_break]
disabled = true

# format = """
# [î‚¶](#9A348E)\
# $directory\
# $git_branch\
# $git_status\
# $nodejs\
# $rust\
# """

# [directory]
# style = "bg:#DA627D"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "â€¦/"

[git_branch]
# format = " $symbol$branch "
# style = "bold gray"
style = "bold white"

[git_commit]
commit_hash_length = 8
style = "bold green"

[git_state]
# format = '($state( $progress_current of $progress_total)) '

[git_metrics]
disabled = false

[git_status]
# conflicted = "âš”ï¸ "
# ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
# behind = "ğŸ¢ Ã—${count}"
# diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
# untracked = "ğŸ›¤ï¸ Ã—${count}"
# stashed = "ğŸ“¦ "
# modified = "ğŸ“ Ã—${count}"
# staged = "ğŸ—ƒï¸ Ã—${count}"
# renamed = "ğŸ“› Ã—${count}"
# deleted = "ğŸ—‘ï¸ Ã—${count}"
# style = "bright-white"
# format = "$all_status$ahead_behind"
conflicted = false
ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = false
stashed = "ğŸ“¦ "
modified = "ğŸ“ "
staged = "ğŸ—ƒï¸ Ã—${count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸ Ã—${count}"
style = "bold red"
format = "$modified$ahead_behind"
disabled = true

[rust]
# format = "$symbol$version "
# style = "bold green"
disabled = true

[cmd_duration]
disabled = true
